import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { DependentContextProvider } from "@/context/DependentContext";
import { TreatmentContextProvider } from "@/context/TreatmentContext";
import { ReminderContextProvider } from "@/context/ReminderContext";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lembre Bem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const pathName = usePathname();
  // console.log(pathName)
  // const isHomePage = router === "/";

  return (
    <html lang="en">
      <head></head>
      <body className={`${inter.className} layout-body`}>
        <ChakraProvider>
          <ReminderContextProvider>
            <TreatmentContextProvider>
              <DependentContextProvider>
                <div className="layout">
                  <Header/>
                {/* {pathName !== "/" ?? <Header />} */}
                  <main className="layout-content">{children}</main>
                {/* {pathName !== "/" ?? <Footer />} */}
                <Footer/>

                </div>
              </DependentContextProvider>
            </TreatmentContextProvider>
          </ReminderContextProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
